name: build and deploy to pages 🥳

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version:
          - 14.x

    steps:
      - name: checkout code 💣
        uses: actions/checkout@v3

      - name: create .env file for tests 💫
        env:
           REACT_APP_PARTITION_KEY: ${{ secrets.REACT_APP_PARTITION_KEY }}
           REACT_APP_SCOREBOARD_RESULTS_ENDPOINT: ${{ secrets.REACT_APP_SCOREBOARD_RESULTS_ENDPOINT }}
           REACT_APP_POST_NEW_SCORE_ENDPOINT: ${{ secrets.REACT_APP_POST_NEW_SCORE_ENDPOINT }}
        run: |
          touch .env
          echo REACT_APP_PROD_IMG_PATH='./mage.gif' > .env
          echo REACT_APP_PROD_COIN_IMG_PATH='./dodg.gif' >> .env
          echo REACT_APP_PROD_GAME_OVER_GIRL_PATH='./gameOverGirl.png' >> .env
          echo REACT_APP_PARTITION_KEY=${REACT_APP_PARTITION_KEY} >> .env
          echo REACT_APP_SCOREBOARD_RESULTS_ENDPOINT=${REACT_APP_SCOREBOARD_RESULTS_ENDPOINT} >> .env
          echo REACT_APP_POST_NEW_SCORE_ENDPOINT=${REACT_APP_POST_NEW_SCORE_ENDPOINT} >> .env

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install node_modules
        run: npm ci

      - name: Build the app 👾
        run: npm run build # output is in the build folder

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: build # The folder the action should deploy.
