name: CI

on:
  push:
    branches:
      - gh-pages

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v1

    - name: Build
      env:
        REACT_APP_PARTITION_KEY: ${{ secrets.REACT_APP_PARTITION_KEY }}
        REACT_APP_POST_NEW_SCORE_ENDPOINT: ${{ secrets.REACT_APP_POST_NEW_SCORE_ENDPOINT }}
        REACT_APP_SCOREBOARD_RESULTS_ENDPOINT: ${{ secrets.REACT_APP_SCOREBOARD_RESULTS_ENDPOINT }}

    - name: Deploy
      uses: SergiyFomin/github-pages-deploy-action@releases/v3
      with:
        BRANCH: gh-pages
        FOLDER: build
